# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Apple iBridge (T1) touch bar / ALS drivers
#

obj-$(CONFIG_HID_APPLE_IBRIDGE)	+= apple-ibridge.o
obj-$(CONFIG_HID_APPLE_IB_TB)	+= apple-ib-tb.o
obj-$(CONFIG_HID_APPLE_IB_ALS)	+= apple-ib-als.o
